const en={
name:'English',
dict:{
'SMS Metasprite Editor':'SMS Metasprite Editor',
'📂 Importer PNG':'📂 Import PNG',
'📋 Nouveau':'📋 New',
'Couleur 0':'Color 0',
'Zoom':'Zoom',
'💾 Sauver':'💾 Save',
'📂 Charger':'📂 Load',
'Nom de la planche':'Sheet name',
'ex: mini_iridium':'e.g. mini_iridium',
'Configuration de la planche':'Sheet configuration',
'Tiles':'Tiles',
'Mode':'Mode',
'Preload (VRAM)':'Preload (VRAM)',
'Dynamique':'Dynamic',
'Overlap':'Overlap',
'Non':'No',
'Oui':'Yes',
'Start tile':'Start tile',
'Mode simple':'Simple mode',
'Découpe simple':'Simple cut',
'Horizontal':'Horizontal',
'Vertical':'Vertical',
'✂ Découper la planche':'✂ Cut sheet',
'Mode mémoire':'Memory mode',
'Preload (préchargé)':'Preload',
'Dynamique (streaming)':'Dynamic streaming',
'Taille des sprites':'Sprite size',
'Mode d\'édition':'Editing mode',
'Complexe (collision, attributs)':'Complex (collision, attributes)',
'Simple (adresses tuiles seules)':'Simple (tile addresses only)',
'Découpe avec overlap':'Cut with overlap',
'Non (déplacer les blocs)':'No (move blocks)',
'Oui (tout peut chevaucher)':'Yes (everything can overlap)',
'Attributs dans l\'export .inc':'Attributes in .inc export',
'⇪ Importer config (.json)':'⇪ Import config (.json)',
'Appliquer':'Apply',
'Annuler':'Cancel',
'Séparation':'Pixel gap',
'✂ Découper toute la planche':'✂ Cut whole sheet',
'Animations':'Animations',
'+ Ajouter animation':'+ Add animation',
'Frames —':'Frames —',
'Autogen mirroirs :':'Autogen mirrors:',
'Attributs frame —':'Frame attributes —',
'+ Frame':'+ Frame',
'+ Cloner':'+ Clone',
'+ Importer':'+ Import',
'⇄ Déplacer vers une anim…':'⇄ Move to anim…',
'Déplacer':'Move',
'✂ Découpe auto (zone)':'✂ Auto cut (zone)',
'🗑 Vider les blocs':'🗑 Clear blocks',
'↺ Annuler suppression':'↺ Undo delete',
'bloc(s) sélectionné(s)':'selected block(s)',
'↗ Vers nouvelle frame':'↗ To new frame',
'🗑 Supprimer la sélection':'🗑 Delete selection',
'☐ Éditer boîte collision':'☐ Edit collision box',
'↺ Réinit. boîte (= blocs)':'↺ Reset box (= blocks)',
'Valider':'OK',
'🗑 Tout supprimer':'🗑 Delete all',
'Importer une planche PNG pour commencer':'Import a PNG sprite sheet to start',
'Importer PNG':'Import PNG',
'Preview':'Preview',
'Afficher contour de bloc':'Show block outline',
'Palette':'Palette',
'Tile Bank':'Tile Bank',
'Dédupliquer':'Deduplicate',
'Totaux :':'Total:',
'· Uniques :':'· Unique:',
'Anims :':'Anims:',
'· Frames :':'· Frames:',
'Image :':'Image:',
'Range :':'Range:',
'Poids (BIN) :':'Size (BIN):',
'Tiles peu occupés':'Low-occupancy tiles',
'Seuil':'Threshold',
'Metasprites infos':'Metasprite info',
'⬇ Exporter ASM (.inc)':'⬇ Export to ASM',
'⬇ Exporter pour DevkitSMS (.c/.h)':'⬇ Export for DevkitSMS',
'Découpe en cours…':'Cutting…',
'Image précédente':'Previous frame',
'Image suivante':'Next frame',
'Opacité de la couleur 0 dans la preview':'Color 0 opacity in preview',
'Opacité de la couleur d\'index 0 (baisser pour voir les contours sur fond uni)':'Opacity of color index 0 (lower it to see outlines on a solid background)',
'Autoriser le chevauchement des blocs lors de la découpe auto':'Allow blocks to overlap during auto-cut',
'Index du 1er tile (0-447)':'First tile index (0-447)',
'Découpe la planche depuis le haut/gauche selon les dimensions choisies':'Cut the sheet from the top-left using the selected dimensions',
'Importer la configuration depuis un autre projet .json':'Import configuration from another .json project',
'Écart de pixels vides séparant deux sprites (1 = très collé, 32 = très espacé)':'Gap of empty pixels separating two sprites (1 = very close, 32 = very spaced)',
'Détecte les sprites de la planche et crée une frame par sprite':'Detect sprites in the sheet and create one frame per sprite',
'Déplacer cette frame vers une autre animation':'Move this frame to another animation',
'Découpe automatique sur une zone (selon mode dynamique/preload)':'Auto-cut a zone (depending on dynamic/preload mode)',
'Supprimer tous les blocs de la frame courante':'Delete all blocks from the current frame',
'Annuler la dernière suppression (Ctrl+Z)':'Undo the last deletion (Ctrl+Z)',
'Déplacer la sélection vers une nouvelle frame':'Move selection to a new frame',
'Supprimer les blocs sélectionnés':'Delete selected blocks',
'Supprimer toutes les animations et frames':'Delete all animations and frames',
'Planche PNG horizontale':'Horizontal PNG sheet',
'Binaire planaire SMS':'SMS planar binary',
'Compression PS Gaiden (.psgcompr)':'PS Gaiden compression (.psgcompr)',
'Compression ZX7 (.zx7)':'ZX7 compression (.zx7)',
'Définitions metasprites WLA-DX (.inc)':'WLA-DX metasprite definitions (.inc)',
'Export DevkitSMS en C/H':'DevkitSMS C/H export',
'bit 0 (LSB) → bit 7 (MSB) · nom asm + description':'bit 0 (LSB) → bit 7 (MSB) · asm name + description',
'nom':'name',
'description':'description',
'Configuration appliquée':'Configuration applied',
'JSON invalide':'Invalid JSON',
'Sélectionner une frame (non clonée)':'Select a frame (not a clone)',
'Aucune frame à importer':'No frame to import',
'Sélectionner une frame':'Select a frame',
'Nouvelle animation':'New animation',
'Nom de l\'animation :':'Animation name:',
'Cliquer/glisser pour déplacer la frame':'Click/drag to move the frame',
'Cliquer/glisser pour déplacer l’animation':'Click/drag to move the animation',
'Repartir à zéro ? Les données non sauvegardées seront perdues.':'Start over? Unsaved data will be lost.',
'Remplacer toute la configuration actuelle (mode, taille, mode simple, attributs) par celle de « {name} » ?':'Replace the current configuration (mode, size, simple mode, attributes) with “{name}”?',
'Taille non concordante avec la découpe choisie.':'Size does not match the selected cut dimensions.',
'Renommer :':'Rename:',
'Supprimer animation + frames ?':'Delete animation + frames?',
'Tout supprimer ?\n\nToutes les animations et les {n} frame{s} seront supprimées.':'Delete everything?\n\nAll animations and {n} frame{s} will be deleted.',
'Aucune animation à supprimer':'No animation to delete',
'Animations et frames supprimées':'Animations and frames deleted',
'Aucun bloc sélectionné':'No block selected',
'Activer le mode simple':'Enable simple mode',
'Aucune image':'No image',
'Projet chargé :':'Project loaded:',
'Projet chargé (sans image)':'Project loaded (without image)',
'largeur {size} non multiple de {cut}':'width {size} is not a multiple of {cut}',
'hauteur {size} non multiple de {cut}':'height {size} is not a multiple of {cut}',
'découpe {w}×{h}':'cut {w}×{h}',
'Taille non concordante : PNG {iw}×{ih} px, découpe {cw}×{ch} px.\n{details}':'Size mismatch: PNG {iw}×{ih} px, cut {cw}×{ch} px.\n{details}',
'Transparence (0)':'Transparency (0)',
'Transparence de la couleur d\'index 0 (baisser pour voir les contours sur fond uni)':'Transparency of color index 0 (lower it to see outlines on a solid background)',
'Importer un PNG pour calculer la grille.':'Import a PNG to calculate the grid.',
'PNG {iw}×{ih} · découpe {cw}×{ch}':'PNG {iw}×{ih} · cut {cw}×{ch}',
'{cols}×{rows} = {n} case{s}':'{cols}×{rows} = {n} cell{s}',
'{n} frame{s} créée{s2}':'{n} frame{s} created',
'{n} vide{s} ignorée{s2}':'{n} empty cell{s} skipped',
'{n} couleur{s}':'{n} color{s}',
'(affiché{s})':'(shown)',
'{n} tile{s} sous le seuil':'{n} tile{s} below threshold'
}
};
window.MetaLangPacks=window.MetaLangPacks||{};
window.MetaLangPacks.en=en;
