const fr={
name:'Français',
dict:{
'SMS Metasprite Editor':'SMS Metasprite Editor',
'📂 Importer PNG':'📂 Importer PNG',
'📋 Nouveau':'📋 Nouveau',
'Couleur 0':'Couleur 0',
'Zoom':'Zoom',
'💾 Sauver':'💾 Sauver',
'📂 Charger':'📂 Charger',
'Nom de la planche':'Nom de la planche',
'ex: mini_iridium':'ex: mini_iridium',
'Configuration de la planche':'Configuration de la planche',
'Tiles':'Tiles',
'Mode':'Mode',
'Preload (VRAM)':'Preload (VRAM)',
'Dynamique':'Dynamique',
'Overlap':'Overlap',
'Non':'Non',
'Oui':'Oui',
'Start tile':'Start tile',
'Mode simple':'Mode simple',
'Découpe simple':'Découpe simple',
'Horizontal':'Horizontal',
'Vertical':'Vertical',
'✂ Découper la planche':'✂ Découper la planche',
'Mode mémoire':'Mode mémoire',
'Preload (préchargé)':'Preload (préchargé)',
'Dynamique (streaming)':'Dynamique (streaming)',
'Taille des sprites':'Taille des sprites',
'Mode d\'édition':'Mode d\'édition',
'Complexe (collision, attributs)':'Complexe (collision, attributs)',
'Simple (adresses tuiles seules)':'Simple (adresses tuiles seules)',
'Découpe avec overlap':'Découpe avec overlap',
'Non (déplacer les blocs)':'Non (déplacer les blocs)',
'Oui (tout peut chevaucher)':'Oui (tout peut chevaucher)',
'Attributs dans l\'export .inc':'Attributs dans l\'export .inc',
'⇪ Importer config (.json)':'⇪ Importer config (.json)',
'Appliquer':'Appliquer',
'Annuler':'Annuler',
'Séparation':'Espace pixels',
'✂ Découper toute la planche':'✂ Découper toute la planche',
'Animations':'Animations',
'+ Ajouter animation':'+ Ajouter animation',
'Frames —':'Frames —',
'Autogen mirroirs :':'Autogen mirroirs :',
'Attributs frame —':'Attributs frame —',
'+ Frame':'+ Frame',
'+ Cloner':'+ Cloner',
'+ Importer':'+ Importer',
'⇄ Déplacer vers une anim…':'⇄ Déplacer vers une anim…',
'Déplacer':'Déplacer',
'✂ Découpe auto (zone)':'✂ Découpe auto (zone)',
'🗑 Vider les blocs':'🗑 Vider les blocs',
'↺ Annuler suppression':'↺ Annuler suppression',
'bloc(s) sélectionné(s)':'bloc(s) sélectionné(s)',
'↗ Vers nouvelle frame':'↗ Vers nouvelle frame',
'🗑 Supprimer la sélection':'🗑 Supprimer la sélection',
'☐ Éditer boîte collision':'☐ Éditer boîte collision',
'↺ Réinit. boîte (= blocs)':'↺ Réinit. boîte (= blocs)',
'Valider':'Valider',
'🗑 Tout supprimer':'🗑 Tout supprimer',
'Importer une planche PNG pour commencer':'Importer une planche PNG pour commencer',
'Importer PNG':'Importer PNG',
'Preview':'Preview',
'Afficher contour de bloc':'Afficher contour de bloc',
'Palette':'Palette',
'Tile Bank':'Tile Bank',
'Dédupliquer':'Dédupliquer',
'Totaux :':'Totaux :',
'· Uniques :':'· Uniques :',
'Anims :':'Anims :',
'· Frames :':'· Frames :',
'Image :':'Image :',
'Range :':'Range :',
'Poids (BIN) :':'Poids (BIN) :',
'Tiles peu occupés':'Tiles peu occupés',
'Seuil':'Seuil',
'Metasprites infos':'Metasprites infos',
'⬇ Exporter ASM (.inc)':'⬇ Exporter en  ASM',
'⬇ Exporter pour DevkitSMS (.c/.h)':'⬇ Exporter pour DevkitSMS',
'Découpe en cours…':'Découpe en cours…',
'Image précédente':'Image précédente',
'Image suivante':'Image suivante',
'Opacité de la couleur 0 dans la preview':'Opacité de la couleur 0 dans la preview',
'Opacité de la couleur d\'index 0 (baisser pour voir les contours sur fond uni)':'Opacité de la couleur d\'index 0 (baisser pour voir les contours sur fond uni)',
'Autoriser le chevauchement des blocs lors de la découpe auto':'Autoriser le chevauchement des blocs lors de la découpe auto',
'Index du 1er tile (0-447)':'Index du 1er tile (0-447)',
'Découpe la planche depuis le haut/gauche selon les dimensions choisies':'Découpe la planche depuis le haut/gauche selon les dimensions choisies',
'Importer la configuration depuis un autre projet .json':'Importer la configuration depuis un autre projet .json',
'Écart de pixels vides séparant deux sprites (1 = très collé, 32 = très espacé)':'Écart de pixels vides séparant deux sprites (1 = très collé, 32 = très espacé)',
'Détecte les sprites de la planche et crée une frame par sprite':'Détecte les sprites de la planche et crée une frame par sprite',
'Déplacer cette frame vers une autre animation':'Déplacer cette frame vers une autre animation',
'Découpe automatique sur une zone (selon mode dynamique/preload)':'Découpe automatique sur une zone (selon mode dynamique/preload)',
'Supprimer tous les blocs de la frame courante':'Supprimer tous les blocs de la frame courante',
'Annuler la dernière suppression (Ctrl+Z)':'Annuler la dernière suppression (Ctrl+Z)',
'Déplacer la sélection vers une nouvelle frame':'Déplacer la sélection vers une nouvelle frame',
'Supprimer les blocs sélectionnés':'Supprimer les blocs sélectionnés',
'Supprimer toutes les animations et frames':'Supprimer toutes les animations et frames',
'Planche PNG horizontale':'Planche PNG horizontale',
'Binaire planaire SMS':'Binaire planaire SMS',
'Compression PS Gaiden (.psgcompr)':'Compression PS Gaiden (.psgcompr)',
'Compression ZX7 (.zx7)':'Compression ZX7 (.zx7)',
'Définitions metasprites WLA-DX (.inc)':'Définitions metasprites WLA-DX (.inc)',
'Export DevkitSMS en C/H':'Export DevkitSMS en C/H',
'bit 0 (LSB) → bit 7 (MSB) · nom asm + description':'bit 0 (LSB) → bit 7 (MSB) · nom asm + description',
'nom':'nom',
'description':'description',
'Configuration appliquée':'Configuration appliquée',
'JSON invalide':'JSON invalide',
'Sélectionner une frame (non clonée)':'Sélectionner une frame (non clonée)',
'Aucune frame à importer':'Aucune frame à importer',
'Sélectionner une frame':'Sélectionner une frame',
'Nouvelle animation':'Nouvelle animation',
'Nom de l\'animation :':'Nom de l\'animation :',
'Cliquer/glisser pour déplacer la frame':'Cliquer/glisser pour déplacer la frame',
'Cliquer/glisser pour déplacer l’animation':'Cliquer/glisser pour déplacer l’animation',
'Repartir à zéro ? Les données non sauvegardées seront perdues.':'Repartir à zéro ? Les données non sauvegardées seront perdues.',
'Remplacer toute la configuration actuelle (mode, taille, mode simple, attributs) par celle de « {name} » ?':'Remplacer toute la configuration actuelle (mode, taille, mode simple, attributs) par celle de « {name} » ?',
'Taille non concordante avec la découpe choisie.':'Taille non concordante avec la découpe choisie.',
'Renommer :':'Renommer :',
'Supprimer animation + frames ?':'Supprimer animation + frames ?',
'Tout supprimer ?\n\nToutes les animations et les {n} frame{s} seront supprimées.':'Tout supprimer ?\n\nToutes les animations et les {n} frame{s} seront supprimées.',
'Aucune animation à supprimer':'Aucune animation à supprimer',
'Animations et frames supprimées':'Animations et frames supprimées',
'Aucun bloc sélectionné':'Aucun bloc sélectionné',
'Activer le mode simple':'Activer le mode simple',
'Aucune image':'Aucune image',
'Projet chargé :':'Projet chargé :',
'Projet chargé (sans image)':'Projet chargé (sans image)',
'largeur {size} non multiple de {cut}':'largeur {size} non multiple de {cut}',
'hauteur {size} non multiple de {cut}':'hauteur {size} non multiple de {cut}',
'découpe {w}×{h}':'découpe {w}×{h}',
'Taille non concordante : PNG {iw}×{ih} px, découpe {cw}×{ch} px.\n{details}':'Taille non concordante : PNG {iw}×{ih} px, découpe {cw}×{ch} px.\n{details}',
'Transparence (0)':'Transparence (0)',
'Transparence de la couleur d\'index 0 (baisser pour voir les contours sur fond uni)':'Transparence de la couleur d\'index 0 (baisser pour voir les contours sur fond uni)',
'Importer un PNG pour calculer la grille.':'Importer un PNG pour calculer la grille.',
'PNG {iw}×{ih} · découpe {cw}×{ch}':'PNG {iw}×{ih} · découpe {cw}×{ch}',
'{cols}×{rows} = {n} case{s}':'{cols}×{rows} = {n} case{s}',
'{n} frame{s} créée{s2}':'{n} frame{s} créée{s2}',
'{n} vide{s} ignorée{s2}':'{n} vide{s} ignorée{s2}',
'{n} couleur{s}':'{n} couleur{s}',
'(affiché{s})':'(affiché{s})',
'{n} tile{s} sous le seuil':'{n} tile{s} sous le seuil'
}
};
window.MetaLangPacks=window.MetaLangPacks||{};
window.MetaLangPacks.fr=fr;
